<?php
require_once 'config/database.php';
$db = getDB();

try {
    $stmt = $db->prepare("UPDATE products SET descricao_mtc = ?, modo_utilizacao = ?, restricoes = ? WHERE id = ?");

    $stmt->execute(["Este suplemento, disponível em embalagem de 60 cápsulas, foi desenvolvido para apoiar processos de emagrecimento, ajudando na redução da gordura corporal e localizada, no combate à celulite e no controlo eficaz do apetite. A sua fórmula completa promove uma sensação de saciedade imediata e estimula o metabolismo através de um efeito termogénico que evita a absorção de gorduras pelo organismo. Para além de contribuir para a diminuição da retenção de líquidos e facilitar o trânsito intestinal, atua também no equilíbrio metabólico, ajudando a controlar os níveis de glicémia e de colesterol. Graças à presença de vitaminas e minerais na sua composição, auxilia ainda na redução do cansaço e da fadiga, proporcionando a energia necessária para o dia a dia.", "A toma geral recomendada é de duas cápsulas antes das duas refeições principais, acompanhadas por um a dois copos de água.", "O seu uso é contraindicado em caso de alergias, dificuldade de deglutição, e durante a gravidez ou amamentação, exceto sob indicação médica. Doentes diabéticos devem efetuar um controlo regular devido à ação hipoglicemiante natural do produto.", 1]);

    $stmt->execute(["Este suplemento, disponível em embalagem de 60 cápsulas, foi desenvolvido para auxiliar na perda de gordura, sendo especialmente indicado para processos de emagrecimento associados a níveis elevados de colesterol ou glicose no sangue. A sua fórmula combina o mineral Crómio com extratos botânicos (como Garcinia Cambogia, Gengibre, Aloé Vera e Cascara Sagrada) para atuar de forma dupla no metabolismo e no sistema digestivo. Para além de moderar o apetite e possuir uma ação termogénica que ajuda a reduzir a absorção de gorduras e hidratos de carbono, destaca-se por ser altamente eficaz no combate à obstipação, estimulando a mobilidade intestinal, facilitando a evacuação e diminuindo a retenção de líquidos.", "A toma recomendada é de um comprimido duas vezes ao dia, preferencialmente após as duas refeições principais, sendo fundamental associar um consumo reforçado de água (cerca de 2 litros por dia).", "Contraindicado para menores de 12 anos, grávidas, mulheres a amamentar ou pessoas com alergia aos seus constituintes. Em casos de obstipação crónica, o tratamento pode estender-se por um período de 3 a 6 meses.", 2]);

    $stmt->execute(["Este suplemento, disponível numa embalagem de 20 ampolas, foi desenvolvido para combater ativamente a fadiga física, mental e emocional, otimizando o rendimento cerebral, a memória e a capacidade de concentração. A sua fórmula revitalizante atua no sistema nervoso e no metabolismo produtor de energia, combinando Vitamina C e vitaminas do complexo B (como B6, Niacina e Riboflavina) com extratos naturais estimulantes, onde se destacam o Guaraná, Ginseng Coreano, Rhodiola Rosea e Gengibre. Em conjunto, estes ingredientes ajudam a combater o esgotamento psicológico e a astenia, melhoram a recuperação muscular e a performance desportiva, e auxiliam no equilíbrio das digestões e no controlo do colesterol e da glicémia.", "A toma diária recomendada é de uma ampola diluída em 200 ml de água, preferencialmente de manhã. Em casos agudos pode ser tomado até os sintomas desaparecerem; em situações crónicas, recomendam-se ciclos contínuos de 3 a 6 meses.", "Devido à presença de cafeína, não deve ser consumido antes de dormir. Doentes diabéticos devem fazer um controlo regular da glicémia. Contraindicado para menores de 12 anos, grávidas e mulheres a amamentar.", 3]);

    $stmt->execute(["Este suplemento, disponível numa embalagem de 60 cápsulas, foi desenvolvido para apoiar o normal funcionamento da estrutura óssea, muscular e das cartilagens, destacando-se pela sua forte ação analgésica e anti-inflamatória. A sua fórmula rigorosa combina vitaminas (C e D), minerais (como o Manganês) e componentes estruturais como a Glucosamina, Condroitina e MSM, potenciados por extratos naturais de Curcuma e Boswellia. Em conjunto, estes ingredientes ajudam a reduzir o inchaço articular e a rigidez, promovem a formação de colagénio, atenuam a fadiga muscular e protegem as células contra o stress oxidativo. Especialmente indicado para reumatismo, artroses, artrite, dores ciáticas, fibromialgia e recuperação de fraturas ou lesões.", "A toma diária geral é de três cápsulas distribuídas pelas principais refeições, podendo ser reduzida para duas cápsulas numa fase de manutenção. A duração varia de acordo com a necessidade, desde a toma até ao desaparecimento de sintomas até períodos de 3 meses a 1 ano.", "Contraindicado para menores de 18 anos, grávidas e mulheres a amamentar. Utilizadores de anticoagulantes ou com obstrução hepato-biliar devem consultar um médico antes de iniciar a toma.", 4]);

    $avisos_fitoterapia = "Produto sujeito a depósito. Agitar antes de tomar. Após abertura consumir no prazo de 3 meses. Devido à presença de extrato natural de plantas, o aspeto do produto poderá variar ligeiramente. Evite o produto em caso de alergia ou sensibilidade a algum dos ingredientes. Manter fora do alcance das crianças. Se estiver grávida, a amamentar, a tomar alguma especialidade farmacêutica ou se sofre de alguma doença, consulte o seu médico ou técnico de saúde antes de tomar este suplemento. Não exceder a dose diária recomendada. Conservar em local seco e fresco, sem exposição direta à luz.";
    $modo_fitoterapia = "Tomar 50 gotas diluídas em água 2 vezes ao dia, ou de acordo com a recomendação de um terapeuta.";

    $stmt->execute(["Suplemento alimentar fitoterapêutico à base de plantas de medicina tradicional chinesa, 100% natural. Indicado para regulação do sistema digestivo e equilíbrio metabólico. Ingredientes: Ramo Cinnamomi, Raiz Paeoniae albae, Rizoma Zingiberis, Raiz Glycyrrhizae, Fruto Zizyphi jujubae.", $modo_fitoterapia, $avisos_fitoterapia, 5]);

    $stmt->execute(["Suplemento alimentar fitoterapêutico à base de plantas de medicina tradicional chinesa, 100% natural. Ação: Retira calor no Qi. Purifica calor perverso (Pulmão/Estômago). Regenera produção de líquidos orgânicos, acalma a sede. Indicado para doenças infecciosas com sintomas de forte calor, irritabilidade, agitação, cefaleias e tosse com expectoração. Ingredientes: Fruto Mori, Erva Houttuyniae, Rizoma Anemarrhenae, Raiz Glycyrrhizae.", $modo_fitoterapia, $avisos_fitoterapia, 6]);

    $stmt->execute(["Suplemento alimentar fitoterapêutico à base de plantas de medicina tradicional chinesa, 100% natural. Tonifica o Baço e o Estômago, fortalece o Qi. Indicado para fraqueza digestiva, falta de energia e astenia geral. Ingredientes: Raiz Codonopsis, Rizoma Atractylodis macrocephalae, Cogumelo Poriae albae, Raiz Glycyrrhizae.", $modo_fitoterapia, $avisos_fitoterapia, 7]);

    $stmt->execute(["Suplemento alimentar fitoterapêutico à base de plantas de medicina tradicional chinesa, 100% natural. Indicado para astenia geral profunda e crónica, fadiga, impotência, fraqueza lombar, enurese noturna e cura de rejuvenescimento. Grande tonificação do Yin e do Yang, do Sangue e da Energia.", $modo_fitoterapia, "Desaconselhado a pessoas do tipo Yang. " . $avisos_fitoterapia, 8]);

    $stmt->execute(["Suplemento alimentar fitoterapêutico à base de plantas de medicina tradicional chinesa, 100% natural. Elimina Vento, frio e humidade. Tonifica o Rim. Reforça os músculos, tendões e ossos. Ação analgésica. Indicado para lombalgia crónica, dores crónicas das costas, fraqueza dos joelhos e lumbago crónico.", $modo_fitoterapia, $avisos_fitoterapia, 9]);

    $stmt->execute(["Suplemento alimentar fitoterapêutico à base de plantas de medicina tradicional chinesa, 100% natural. Indicado para hemorroidas, hemorragias intestinais, rectorragias e fezes sanguinolentas. Hemostático, adstringente e hipotensivo. Dispersa o Vento, elimina o Calor e a Humidade.", $modo_fitoterapia, $avisos_fitoterapia, 10]);

    $stmt->execute(["Suplemento alimentar fitoterapêutico à base de plantas de medicina tradicional chinesa, 100% natural. Indicado para hemorroidas, dores epigástricas, prisão de ventre, úlceras da boca e língua, hemorragia nasal, gengivorragias, cefaleias e falta de apetite. Nutre o Yin do Estômago. Clarifica o Fogo profundo do Estômago.", $modo_fitoterapia, $avisos_fitoterapia, 11]);

    $stmt->execute(["Suplemento alimentar fitoterapêutico à base de plantas de medicina tradicional chinesa, 100% natural. Indicado para astenia, cansaço, tonturas, distúrbios de memória e concentração, líbido diminuída, senescência prematura, atraso de crescimento e lumbago. Tonifica o Yin e Yang em geral, especialmente a nível do Rim.", $modo_fitoterapia, "Devido à sua ação fortemente tónica sobre o Yang, é desaconselhado a pessoas de tipologia muito Yang. " . $avisos_fitoterapia, 12]);

    $stmt->execute(["Suplemento alimentar fitoterapêutico à base de plantas de medicina tradicional chinesa, 100% natural. Indicado para má circulação, varizes, prevenção e tratamento de AVC e enfarte do miocárdio, dor por estagnação de sangue, traumatismos e hematomas. Ativa a circulação do Sangue e Energia, retira a estase de Sangue.", $modo_fitoterapia, $avisos_fitoterapia, 13]);

    $stmt->execute(["Suplemento alimentar fitoterapêutico à base de plantas de medicina tradicional chinesa, 100% natural. Indicado para garganta inflamada, dores de cabeça, sintomas de constipação, dores articulares, urticária, eczemas e prurido. Dispersa o Vento, o Calor e a Humidade.", $modo_fitoterapia, $avisos_fitoterapia, 14]);

    $stmt->execute(["Suplemento alimentar fitoterapêutico à base de plantas de medicina tradicional chinesa, 100% natural. Indicado para asma, tosse com expectoração viscosa, respiração difícil e ruidosa, plenitude no peito e dificuldade em expectorar. Dispersa e diminui a energia patogénica no Pulmão. Elimina o Flegma-Calor.", $modo_fitoterapia, $avisos_fitoterapia, 15]);

    $stmt->execute(["Suplemento alimentar fitoterapêutico à base de plantas de medicina tradicional chinesa, 100% natural. Indicado para cefaleias de tensão, vertigens, tonturas, convulsões, acessos de calor, entorpecimento dos membros, transpiração nocturna, espasmos, zumbidos, palpitações, insónia e suspiros. Acalma o Fígado e alimenta o Yin.", $modo_fitoterapia, $avisos_fitoterapia, 16]);

    echo "<h2 style='color:green; font-family:sans-serif'>Descrições actualizadas com sucesso!</h2>";
    echo "<p style='font-family:sans-serif'>Todos os 16 produtos foram actualizados.</p>";
    echo "<p style='font-family:sans-serif'><a href='/?page=shop'>Ver loja</a></p>";

} catch (Exception $e) {
    echo "<h2 style='color:red'>Erro: " . $e->getMessage() . "</h2>";
}
